### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by CloudNiner** [jgcobb3/python-azavea-climate#1]
Hi @jgcobb3, thanks for creating this!

I'm one of the developers working at Azavea and we're interested in using this library for a derivative project of ours, but would need a license attached to the project to do so. You can find some basic information at https://choosealicense.com/ on choosing an open source license if you're willing to attach a friendly license to your project.

**Comment by jgcobb3** [comment]
Andrew,

I work for the USDA Southeastern Regional Climate Hub, and I wrote this as
part of my official duties. In short, it's in the  public domain and I've
added a LICENSE as such. If you have any questions, I can be reached at
jgcobb@fs.fed.us

V/r,
John Cobb

**Comment by CloudNiner** [comment]
Great to hear, thanks so much for the quick reply.
